### Master Settings For ArchXtract: Build-062524.py

###
### As this project grows, I will try my best to keep as many things accesable here in the settings
### - B1GBOOM 06-24-2024 | 01:48 AM
###


## Extraction Settings
extract_7z_archives: False
extract_zip_archives: True


## Deleteion Settings
delete_7z_archives: True
delete_zip_archives: True
delete_txt_files: True


## Cores / Worker Settings
max_workers: 5